# -*- coding: utf-8 -*-
"""Pesquisa_Deputados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7SJ6vYk8ajCB_GlCxkoWxVJEieKzOaI
"""

!pip install pandas

import requests
import pandas as pd

class MonitoramentoLegislativo:
    def __init__(self):
        self.base_camara = "https://dadosabertos.camara.leg.br/api/v2"
        self.base_senado = "https://legis.senado.leg.br/dadosabertos"

    def get_deputados_influentes(self, nomes):
        """Busca IDs de deputados específicos na API da Câmara"""
        print(f"\n--- Buscando Deputados na Câmara ---")
        url = f"{self.base_camara}/deputados"
        params = {'ordem': 'ASC', 'ordenarPor': 'nome'}
        response = requests.get(url, params=params).json()

        deputados = [d for d in response['dados'] if d['nome'] in nomes]
        for d in deputados:
            print(f"ID: {d['id']} | Nome: {d['nome']} | Partido: {d['siglaPartido']}")
        return deputados

    def get_discursos_deputado(self, deputado_id):
        """Puxa os últimos discursos de um deputado"""
        url = f"{self.base_camara}/deputados/{deputado_id}/discursos"
        params = {'itens': 5} # Limitando para o terminal não poluir
        response = requests.get(url, params=params).json()
        return response['dados']

    def get_senadores_atuais(self, nomes):
        """Busca IDs de senadores específicos na API do Senado"""
        print(f"\n--- Buscando Senadores no Senado ---")
        url = f"{self.base_senado}/senador/lista/atual"
        headers = {'Accept': 'application/json'}
        response = requests.get(url, headers=headers).json()

        lista = response['ListaParlamentarEmExercicio']['Parlamentares']['Parlamentar']
        senadores = [s for s in lista if s['IdentificacaoParlamentar']['NomeParlamentar'] in nomes]

        for s in senadores:
            ident = s['IdentificacaoParlamentar']
            print(f"ID: {ident['CodigoParlamentar']} | Nome: {ident['NomeParlamentar']} | Partido: {ident['SiglaPartidoParlamentar']}")
        return senadores

# --- Execução Exemplo ---

monitor = MonitoramentoLegislativo()

# 1. Definindo alvos de influência (conforme seu texto)
alvos_camara = ["Arthur Lira", "Tabata Amaral", "Erika Hilton", "Guilherme Boulos"]
alvos_senado = [
    "Rodrigo Pacheco",      # Presidente do Senado
    "Randolfe Rodrigues",    # Líder do Governo no Congresso
    "Davi Alcolumbre",      # Presidente da CCJ / Articulador Político
    "Renan Calheiros",      # Influência histórica e relatorias de peso
    "Rogério Marinho",      # Líder da Oposição
    "Jaques Wagner",        # Líder do Governo no Senado
    "Ciro Nogueira",        # Liderança do Bloco Parlamentar / PP
    "Tereza Cristina",      # Liderança da Bancada Ruralista
    "Eduardo Braga",        # Relator de temas econômicos e líder do MDB
    "Otto Alencar"          # Influência em comissões técnicas e PSD
]

# 2. Puxando dados da Câmara
deputados_encontrados = monitor.get_deputados_influentes(alvos_camara)
if deputados_encontrados:
    exemplo_id = deputados_encontrados[0]['id']
    discursos = monitor.get_discursos_deputado(exemplo_id)

    print(f"\nÚltimos discursos de {deputados_encontrados[0]['nome']}:")
    for disc in discursos:
        data = disc['dataHoraInicio'][:10]
        resumo = (disc['keywords'] or "Sem palavras-chave")[:80]
        print(f"[{data}] {resumo}...")

# 3. Puxando dados do Senado
senadores_encontrados = monitor.get_senadores_atuais(alvos_senado)

def debug_camara_discursos(deputado_id):
    url = f"https://dadosabertos.camara.leg.br/api/v2/deputados/{deputado_id}/discursos"
    params = {'itens': 5, 'ordem': 'DESC', 'ordenarPor': 'dataHoraInicio'}
    headers = {'Accept': 'application/json'}

    try:
        response = requests.get(url, params=params, headers=headers)
        data = response.json()

        if not data['dados']:
            print(f"Nenhum discurso encontrado para o ID {deputado_id}.")
            return

        for i, discurso in enumerate(data['dados']):
            print(f"\n--- Discurso {i+1} ---")
            print(f"Data: {discurso.get('dataHoraInicio')}")

            # Tentativa 1: Campo de transcrição direta
            texto = discurso.get('transcricao')

            # Tentativa 2: Algumas vezes a API retorna apenas palavras-chave
            keywords = discurso.get('keywords')

            # Tentativa 3: Verificar se há um link para o texto completo
            link_integra = discurso.get('urlTexto')

            if texto:
                print(f"Texto encontrado: {texto[:200]}...")
            elif keywords:
                print(f"ℹApenas palavras-chave disponíveis: {keywords}")

            if link_integra:
                print(f"Link para a íntegra: {link_integra}")

            if not texto and not keywords and not link_integra:
                print("Este registro existe, mas a API não forneceu conteúdo textual.")

    except Exception as e:
        print(f"Erro na requisição: {e}")

# Teste com o ID do Arthur Lira (160510)
debug_camara_discursos(204534)

import requests
from bs4 import BeautifulSoup

def scrape_senado_discursos(id_senador, qtd=5):
    """Extrai os textos dos últimos 'qtd' discursos do senador."""
    url = f"https://www25.senado.leg.br/web/atividade/pronunciamentos/-/p/parlamentar/{id_senador}"
    headers = {'User-Agent': 'Mozilla/5.0'}

    try:
        response = requests.get(url, headers=headers, timeout=15)
        soup = BeautifulSoup(response.text, 'html.parser')
        tabela = soup.find('table')

        if not tabela: return []

        links_discursos = []
        for linha in tabela.find_all('tr')[1:qtd+1]:
            colunas = linha.find_all('td')
            if colunas:
                link = colunas[0].find('a')
                if link and 'href' in link.attrs:
                    url_d = link['href']
                    links_discursos.append("https://www25.senado.leg.br" + url_d if url_d.startswith('/') else url_d)

        textos = []
        for url_discurso in links_discursos:
            res_discurso = requests.get(url_discurso, headers=headers)
            soup_discurso = BeautifulSoup(res_discurso.text, 'html.parser')
            texto_div = soup_discurso.find('div', class_='texto-integral') or soup_discurso.find('div', id='textoPronunciamento')
            if texto_div:
                textos.append(texto_div.get_text(separator='\n').strip())

        return textos
    except Exception as e:
        print(f"Erro ao raspar: {e}")
        return []

from transformers import AutoTokenizer, AutoModel
import torch

# Carregamento do modelo pré-treinado (Base ou Large)
model_name = "neuralmind/bert-base-portuguese-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

def get_embedding(text):
    # Tokenização e conversão para tensores
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512)

    with torch.no_grad():
        outputs = model(**inputs)

    # Utilizamos a média da última camada oculta como representação vetorial (embedding)
    embeddings = outputs.last_hidden_state.mean(dim=1)
    return embeddings

import requests
import xml.etree.ElementTree as ET

def extrair_e_filtrar_votos(url):
    """
    Busca o XML da URL, extrai aproximadamente 1/4 das votações
    e aplica a lógica de filtragem fornecida.
    """
    headers = {'Accept': 'application/xml'}
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()

        # Parse do XML completo
        root = ET.fromstring(response.content)

        # Localiza todas as votações
        todas_votacoes = root.findall('.//Votacao')
        quantidade = len(todas_votacoes)

        # Pega o primeiro quarto das votações
        limite = max(1, quantidade // 4)
        votos_slice = todas_votacoes[:limite]

        print(f"Total de votações encontradas: {quantidade}")
        print(f"Processando as primeiras {limite} votações (1/4).")

        # Recria um XML parcial para a função de filtragem ou adapta a lógica
        # Para manter a compatibilidade exata com sua função, vamos passar o XML das selecionadas
        # Como a função espera uma string XML, vamos reconstruir um nó raiz temporário
        root_temp = ET.Element('ListaVotacoes')
        for v in votos_slice:
            root_temp.append(v)

        xml_parcial = ET.tostring(root_temp, encoding='unicode')
        return filtrar_votos(xml_parcial)

    except Exception as e:
        return f"Erro ao processar: {e}"

def filtrar_votos(xml_data):
    root = ET.fromstring(xml_data)
    votos_uteis = []

    for votacao in root.findall('.//Votacao'):
        # Ignora votações secretas
        voto_secreto = votacao.find('IndicadorVotacaoSecreta')
        if voto_secreto is not None and voto_secreto.text == 'Sim':
            continue

        ementa_node = votacao.find('.//Ementa')
        voto_node = votacao.find('SiglaDescricaoVoto')
        data_node = votacao.find('.//DataSessao')

        ementa = ementa_node.text if ementa_node is not None else "Sem ementa"
        voto = voto_node.text if voto_node is not None else "N/A"
        data = data_node.text if data_node is not None else "N/A"

        votos_uteis.append({
            "data": data,
            "ementa": ementa,
            "voto": voto
        })
    return votos_uteis

# Execução
url_alvo = "https://legis.senado.leg.br/dadosabertos/senador/5942/votacoes"
resultados = extrair_e_filtrar_votos(url_alvo)

# Exibindo os resultados
import pandas as pd
df_votos = pd.DataFrame(resultados)
display(df_votos)

from torch.nn.functional import cosine_similarity
import pandas as pd

# 1. Pegar discursos do Randolfe Rodrigues (5942)
discursos_lista = scrape_senado_discursos(5942, qtd=3)

# 2. Iterar sobre os votos e comparar com o primeiro discurso (exemplo)
if discursos_lista and not df_votos.empty:
    texto_discurso = discursos_lista[0]
    print(f"Analisando correlação com o discurso: {texto_discurso[:100]}...\n")

    emb_discurso = get_embedding(texto_discurso[:512]) # Limite de tokens do BERT

    correlacoes = []
    for idx, row in df_votos.iterrows():
        emb_ementa = get_embedding(row['ementa'][:512])
        score = cosine_similarity(emb_discurso, emb_ementa).item()
        correlacoes.append(score)

    df_votos['correlacao_discurso'] = correlacoes

    # Mostrar os 5 votos mais relacionados ao discurso
    display(df_votos.sort_values(by='correlacao_discurso', ascending=False).head(5))
else:
    print("Não foram encontrados discursos ou votos para comparar.")

"""### Análise de Coerência Parlamentar
Esta tabela cruza o discurso mais recente com as votações mais relevantes (maior similaridade temática) para verificar se o posicionamento em plenário é condizente com as falas do parlamentar.
"""

import pandas as pd

def classificar_coerencia(row, threshold=0.7):
    if row['correlacao_discurso'] >= threshold:
        return "Coerente (Tema Alinhado)"
    elif row['correlacao_discurso'] >= 0.6:
        return "Parcialmente Alinhado"
    else:
        return "Tema Divergente"

if 'df_votos' in globals() and 'correlacao_discurso' in df_votos.columns:
    # Selecionamos as colunas principais para a tabela de auditoria
    tabela_coerencia = df_votos[[
        'data',
        'ementa',
        'voto',
        'correlacao_discurso'
    ]].copy()

    # Aplicamos a classificação
    tabela_coerencia['Avaliação de Coerência'] = tabela_coerencia.apply(classificar_coerencia, axis=1)

    # Renomeando colunas para melhor leitura
    tabela_coerencia.columns = ['Data', 'Ementa da Votação', 'Voto Proferido', 'Índice de Afinidade', 'Status de Coerência']

    # Exibimos apenas as 10 votações onde o tema do discurso foi mais presente
    resultado_final = tabela_coerencia.sort_values(by='Índice de Afinidade', ascending=False).head(10)

    display(resultado_final)
else:
    print("Execute a célula anterior para gerar os índices de correlação primeiro.")

"""### Análise de Possíveis Incoerências (Menor Afinidade)
Esta tabela exibe as votações que possuem a menor relação temática com o discurso analisado, permitindo identificar áreas de atuação silenciosa ou divergente.
"""

if 'tabela_coerencia' in globals():
    # Exibe as 5 votações com os menores índices de afinidade
    incoerencias_potenciais = tabela_coerencia.sort_values(by='Índice de Afinidade', ascending=True).head(5)

    print("Votações com menor correlação temática ao discurso:")
    display(incoerencias_potenciais)
else:
    print("Execute a célula de análise de coerência primeiro.")

import pandas as pd
from torch.nn.functional import cosine_similarity

def analisar_multiplos_parlamentares(lista_ids, qtd_discursos=1):
    consolidado = []

    for id_senador in lista_ids:
        print(f"\n>>> Analisando Parlamentar ID: {id_senador}...")

        # 1. Busca Discursos e Votos
        discursos = scrape_senado_discursos(id_senador, qtd=qtd_discursos)
        url_votos = f"https://legis.senado.leg.br/dadosabertos/senador/{id_senador}/votacoes"
        votos = extrair_e_filtrar_votos(url_votos)

        if not discursos or not votos:
            print(f"Dados insuficientes para o ID {id_senador}.")
            continue

        # 2. Embedding do Discurso mais recente
        texto_discurso = discursos[0]
        emb_discurso = get_embedding(texto_discurso[:512])

        # 3. Processamento de Afinidade
        for v in votos:
            emb_ementa = get_embedding(v['ementa'][:512])
            score = cosine_similarity(emb_discurso, emb_ementa).item()

            # Classificação
            status = "Coerente" if score >= 0.7 else "Parcialmente Alinhado" if score >= 0.6 else "Tema Divergente"

            consolidado.append({
                'ID Parlamentar': id_senador,
                'Data': v['data'],
                'Ementa': v['ementa'],
                'Voto': v['voto'],
                'Afinidade': round(score, 4),
                'Status': status
            })

    return pd.DataFrame(consolidado)

# Lista de IDs para análise (Exemplo: Randolfe Rodrigues e Rodrigo Pacheco)
ids_alvo = [5942, 5732]
df_monitoramento_global = analisar_multiplos_parlamentares(ids_alvo)

# Exibe o resultado final formatado
display(df_monitoramento_global.sort_values(by=['ID Parlamentar', 'Afinidade'], ascending=[True, False]))